### ISSUE TITLE
Type FileDropDirective is part of the declarations of 2 modules??

### ISSUE THREAD

**Issue by raviranjan528** [Ekito/ng2-cloudinary#8]
Type FileDropDirective is part of the declarations of 2 modules: FileUploadModule and Ng2CloudinaryModule! Please consider moving FileDropDirective to a higher module that imports FileUploadModule and Ng2CloudinaryModule. You can also create a new NgModule that exports and includes FileDropDirective then import that NgModule in FileUploadModule and Ng2CloudinaryModule.

i am not able to understand . please Solve this ?

**Comment by julienboulay** [comment]
Hi @raviranjan528,

This was du to the fact that ng2-file-upload was not supporting Angular2 module at the time of writing ng2-cloudinary component. I decided to import the directive directly to Ng2CloudinaryModule..
As the ng2-file-upload now exports its own module, I've just fixed this issue by importing the module.
This should be fixed in version 0.8.0
